// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// quan_wt
NumericVector quan_wt(NumericVector x, NumericVector probs, Nullable<NumericVector> wt, int type);
RcppExport SEXP _ProUtils_quan_wt(SEXP xSEXP, SEXP probsSEXP, SEXP wtSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(quan_wt(x, probs, wt, type));
    return rcpp_result_gen;
END_RCPP
}
// quan_wt_mat_col
SEXP quan_wt_mat_col(NumericMatrix mat, NumericVector probs, Nullable<NumericMatrix> wt, int type);
RcppExport SEXP _ProUtils_quan_wt_mat_col(SEXP matSEXP, SEXP probsSEXP, SEXP wtSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(quan_wt_mat_col(mat, probs, wt, type));
    return rcpp_result_gen;
END_RCPP
}
// quan_wt_mat_row
SEXP quan_wt_mat_row(NumericMatrix mat, NumericVector probs, Nullable<NumericMatrix> wt, int type);
RcppExport SEXP _ProUtils_quan_wt_mat_row(SEXP matSEXP, SEXP probsSEXP, SEXP wtSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(quan_wt_mat_row(mat, probs, wt, type));
    return rcpp_result_gen;
END_RCPP
}
// addVector
void addVector(NumericVector vec);
RcppExport SEXP _ProUtils_addVector(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    addVector(vec);
    return R_NilValue;
END_RCPP
}
// getMedian
double getMedian();
RcppExport SEXP _ProUtils_getMedian() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getMedian());
    return rcpp_result_gen;
END_RCPP
}
// clearHeaps
void clearHeaps();
RcppExport SEXP _ProUtils_clearHeaps() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clearHeaps();
    return R_NilValue;
END_RCPP
}
// getMinHeap
NumericVector getMinHeap();
RcppExport SEXP _ProUtils_getMinHeap() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getMinHeap());
    return rcpp_result_gen;
END_RCPP
}
// getMaxHeap
NumericVector getMaxHeap();
RcppExport SEXP _ProUtils_getMaxHeap() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getMaxHeap());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ProUtils_quan_wt", (DL_FUNC) &_ProUtils_quan_wt, 4},
    {"_ProUtils_quan_wt_mat_col", (DL_FUNC) &_ProUtils_quan_wt_mat_col, 4},
    {"_ProUtils_quan_wt_mat_row", (DL_FUNC) &_ProUtils_quan_wt_mat_row, 4},
    {"_ProUtils_addVector", (DL_FUNC) &_ProUtils_addVector, 1},
    {"_ProUtils_getMedian", (DL_FUNC) &_ProUtils_getMedian, 0},
    {"_ProUtils_clearHeaps", (DL_FUNC) &_ProUtils_clearHeaps, 0},
    {"_ProUtils_getMinHeap", (DL_FUNC) &_ProUtils_getMinHeap, 0},
    {"_ProUtils_getMaxHeap", (DL_FUNC) &_ProUtils_getMaxHeap, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
