# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quan_wt <- function(x, q = as.numeric( c(0.5)), w = NULL) {
    .Call(`_ProUtils_quan_wt`, x, q, w)
}

quan_wt_mat_col <- function(mat, q = as.numeric( c(0.5)), w = NULL) {
    .Call(`_ProUtils_quan_wt_mat_col`, mat, q, w)
}

quan_wt_mat_row <- function(mat, q = as.numeric( c(0.5)), w = NULL) {
    .Call(`_ProUtils_quan_wt_mat_row`, mat, q, w)
}

addVector <- function(vec) {
    invisible(.Call(`_ProUtils_addVector`, vec))
}

getMedian <- function() {
    .Call(`_ProUtils_getMedian`)
}

clearHeaps <- function() {
    invisible(.Call(`_ProUtils_clearHeaps`))
}

getMinHeap <- function() {
    .Call(`_ProUtils_getMinHeap`)
}

getMaxHeap <- function() {
    .Call(`_ProUtils_getMaxHeap`)
}

